package jiyun.com.doctorsixsixsix.Dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import jiyun.com.doctorsixsixsix.modle.bean.Time;
import jiyun.com.doctorsixsixsix.modle.bean.XueYa;

import jiyun.com.doctorsixsixsix.Dao.TimeDao;
import jiyun.com.doctorsixsixsix.Dao.XueYaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timeDaoConfig;
    private final DaoConfig xueYaDaoConfig;

    private final TimeDao timeDao;
    private final XueYaDao xueYaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timeDaoConfig = daoConfigMap.get(TimeDao.class).clone();
        timeDaoConfig.initIdentityScope(type);

        xueYaDaoConfig = daoConfigMap.get(XueYaDao.class).clone();
        xueYaDaoConfig.initIdentityScope(type);

        timeDao = new TimeDao(timeDaoConfig, this);
        xueYaDao = new XueYaDao(xueYaDaoConfig, this);

        registerDao(Time.class, timeDao);
        registerDao(XueYa.class, xueYaDao);
    }
    
    public void clear() {
        timeDaoConfig.clearIdentityScope();
        xueYaDaoConfig.clearIdentityScope();
    }

    public TimeDao getTimeDao() {
        return timeDao;
    }

    public XueYaDao getXueYaDao() {
        return xueYaDao;
    }

}
